--------------------------------------------------------
--  File created - Вторник-Юли-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SONG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SOUNDTRACKER"."SONG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SOUNDTRACKER"."USERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table SEARCH_HASH
--------------------------------------------------------

  CREATE TABLE "SOUNDTRACKER"."SEARCH_HASH" 
   (	"HASH" NUMBER, 
	"SONG_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SONG
--------------------------------------------------------

  CREATE TABLE "SOUNDTRACKER"."SONG" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(512 BYTE), 
	"ARTIST" VARCHAR2(512 BYTE), 
	"LOCATION" VARCHAR2(2048 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SOUNDTRACKER.SEARCH_HASH
SET DEFINE OFF;
REM INSERTING into SOUNDTRACKER.SONG
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SEARCH_HASH_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUNDTRACKER"."SEARCH_HASH_UK1" ON "SOUNDTRACKER"."SEARCH_HASH" ("HASH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SONG_NAME_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUNDTRACKER"."SONG_NAME_UK" ON "SOUNDTRACKER"."SONG" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SONG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUNDTRACKER"."SONG_PK" ON "SOUNDTRACKER"."SONG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SEARCH_HASH
--------------------------------------------------------

  ALTER TABLE "SOUNDTRACKER"."SEARCH_HASH" ADD CONSTRAINT "SEARCH_HASH_UK1" UNIQUE ("HASH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SOUNDTRACKER"."SEARCH_HASH" MODIFY ("HASH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SONG
--------------------------------------------------------

  ALTER TABLE "SOUNDTRACKER"."SONG" ADD CONSTRAINT "SONG_NAME_UK" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SOUNDTRACKER"."SONG" ADD CONSTRAINT "SONG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SOUNDTRACKER"."SONG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SOUNDTRACKER"."SONG" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SOUNDTRACKER"."SONG" MODIFY ("ARTIST" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SEARCH_HASH
--------------------------------------------------------

  ALTER TABLE "SOUNDTRACKER"."SEARCH_HASH" ADD CONSTRAINT "SONG_ID_FK" FOREIGN KEY ("SONG_ID")
	  REFERENCES "SOUNDTRACKER"."SONG" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_SONG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUNDTRACKER"."BI_SONG" 
  before insert on "SONG"               
  for each row  
begin   
    select "SONG_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER "SOUNDTRACKER"."BI_SONG" ENABLE;
